# Generated by Django 6.0.7 on 2026-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ohin', models.DateField()),
                ('oras_hahu', models.TimeField(blank=True, null=True)),
                ('oras_hotu', models.TimeField(blank=True, null=True)),
                ('atividade', models.CharField(max_length=255)),
                ('deskrisaun', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ohin', 'oras_hahu'],
            },
        ),
    ]
